import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className="h-100vh w-full dark:bg-black bg-white  dark:bg-grid-white/[0.3] bg-grid-black/[0.9] relative flex items-center justify-center"}>{children}</body>
    </html>
  );
}
